import json
from dataclasses import asdict, is_dataclass

from state import State
from utils.ask_llm import ask_llm
from utils.prompt_loader import get_prompt
from utils.pipeline_logger import log_entry

MAX_AUTO_REVISIONS = 2


def _jsonable(value):
    """Helper to serialize dataclasses to dictionary format."""
    if is_dataclass(value):
        return asdict(value)
    return value


def auto_flow_critic(state: State):
    """
    Evaluates the outline/proposed flow generated by Flow Architect.
    Rejects flows with generic outlines or bad transitions to auto-correct them.
    After MAX_AUTO_REVISIONS, the final outline is still evaluated: if it passes
    it proceeds to user review as an auto-approved candidate; if it fails it is
    explicitly marked as requiring human review (never silently treated as passed).
    """
    auto_count = state.get("auto_revision_count", 0)

    flow = state.get("proposed_flow")
    flow_str = json.dumps(_jsonable(flow), ensure_ascii=False, indent=2) if flow else ""

    prompt = get_prompt(
        "auto_flow_critic",
        article_length=state.get("article_length", ""),
        transcript=state.get("transcript", ""),
        summary=state["summary"],
        user_feedback=state.get("user_feedback", ""),
        style_profile=json.dumps(state.get("style_profile", {}), ensure_ascii=False, indent=2),
        proposed_flow=flow_str
    )

    response = ask_llm(prompt=prompt, expect_json=True, task="auto_critic")
    approved = response.get("approved", True)
    rating = response.get("rating", 10.0)
    feedback = (response.get("feedback") or "").strip()
    source_issues = response.get("source_fidelity_issues") or []

    # Surface source-fidelity failures directly in the revision brief.
    if source_issues:
        fidelity_prefix = "Source fidelity failures: " + "; ".join(source_issues)
        feedback = f"{fidelity_prefix}\n{feedback}" if feedback else fidelity_prefix

    if not approved and feedback:
        new_count = auto_count + 1
        if new_count >= MAX_AUTO_REVISIONS:
            print(f"\n[Auto Flow Critic] FINAL outline REJECTED (Rating: {rating}/10) after max revisions — requiring human review.\n")
            return {
                "auto_revision_count": 0,
                "requires_human_review": True,
                "next_action": "flow approval",
                "user_feedback": "",
                "pipeline_log": [
                    log_entry(
                        "Auto Flow Critic", "🤖",
                        f"Final outline rejected (Rating: {rating}/10) after max automatic revisions. "
                        "Requires human review/override — not auto-approved.",
                        {"rating": rating, "source_fidelity_issues": source_issues, "feedback": feedback}
                    )
                ]
            }
        print(f"\n[Auto Flow Critic] REJECTED the outline (Rating: {rating}/10)")
        print(f"Feedback: {feedback}\n")
        return {
            "user_feedback": f"[Auto Critic Flow Revision]: {feedback}",
            "auto_revision_count": new_count,
            "requires_human_review": False,
            "next_action": "flow architect",
            "pipeline_log": [
                log_entry(
                    "Auto Flow Critic", "🤖",
                    f"Rejected outline (Rating: {rating}/10) → Auto-revision #{new_count}",
                    {"rating": rating, "source_fidelity_issues": source_issues, "feedback": feedback}
                )
            ]
        }

    # Approved
    print(f"\n[Auto Flow Critic] APPROVED the outline (Rating: {rating}/10)\n")
    return {
        "auto_revision_count": 0,
        "requires_human_review": False,
        "user_feedback": "",  # Clear old auto-feedback before prompting the user
        "next_action": "flow approval",
        "pipeline_log": [
            log_entry(
                "Auto Flow Critic", "🤖",
                f"Approved outline (Rating: {rating}/10)",
                {"rating": rating}
            )
        ]
    }


def auto_draft_critic(state: State):
    """
    Evaluates the draft for AI-generated tropes, sentence monotony,
    cliche transitions, poor metaphor integration, and author-voice failures.
    After MAX_AUTO_REVISIONS, the final draft is still evaluated: if it passes
    it proceeds to user review as an auto-approved candidate; if it fails it is
    explicitly marked as requiring human review (never silently treated as passed).
    """
    auto_count = state.get("auto_revision_count", 0)

    prompt = get_prompt(
        "auto_draft_critic",
        user_idea=state.get("user_idea", ""),
        article_length=state.get("article_length", ""),
        transcript=state.get("transcript", ""),
        summary=state["summary"],
        flow=json.dumps(_jsonable(state.get("proposed_flow")), ensure_ascii=False, indent=2),
        style_profile=json.dumps(state.get("style_profile", {}), ensure_ascii=False, indent=2),
        draft=state.get("draft", "")
    )

    response = ask_llm(prompt=prompt, expect_json=True, task="auto_critic")
    approved = response.get("approved", True)
    rating = response.get("humanity_rating", 10.0)
    feedback = (response.get("feedback") or "").strip()
    markers = response.get("ai_markers_found", [])
    tone_issues = response.get("tone_issues", [])
    idea_drift = response.get("idea_drift", [])
    author_voice_issues = response.get("author_voice_issues", [])
    unsupported = response.get("unsupported_inventions") or []

    # UNSUPPORTED INVENTION is a hard rejection, regardless of the model's verdict.
    if unsupported and approved:
        approved = False
    if unsupported:
        feedback = (
            f"UNSUPPORTED INVENTIONS (source violations): {'; '.join(unsupported)}\n{feedback}"
            if feedback else
            "UNSUPPORTED INVENTIONS (source violations): " + "; ".join(unsupported)
        )

    if not approved and feedback:
        new_count = auto_count + 1
        if new_count >= MAX_AUTO_REVISIONS:
            print(f"\n[Auto Draft Critic] FINAL draft REJECTED (Humanity Rating: {rating}/10) after max revisions — requiring human review.\n")
            if markers:
                print(f"AI Markers Found: {', '.join(markers)}")
            if author_voice_issues:
                print(f"Author Voice Issues: {', '.join(author_voice_issues)}")
            print(f"Feedback: {feedback}\n")
            return {
                "auto_revision_count": 0,
                "requires_human_review": True,
                "next_action": "article approval",
                "user_feedback": "",
                "pipeline_log": [
                    log_entry(
                        "Auto Draft Critic", "🤖",
                        f"Final draft rejected (Rating: {rating}/10) after max automatic revisions. "
                        "Requires human review/override — not auto-approved.",
                        {
                            "rating": rating,
                            "markers": markers,
                            "tone_issues": tone_issues,
                            "author_voice_issues": author_voice_issues,
                            "idea_drift": idea_drift,
                            "unsupported_inventions": unsupported,
                            "feedback": feedback,
                        }
                    )
                ]
            }
        print(f"\n[Auto Draft Critic] REJECTED the draft (Humanity Rating: {rating}/10)")
        if markers:
            print(f"AI Markers Found: {', '.join(markers)}")
        if author_voice_issues:
            print(f"Author Voice Issues: {', '.join(author_voice_issues)}")
        print(f"Feedback: {feedback}\n")

        return {
            "user_feedback": (
                f"[Auto Critic Draft Revision]: {feedback}\n"
                f"Fix AI markers: {', '.join(markers)}\n"
                f"Fix tone/style issues: {', '.join(tone_issues)}\n"
                f"Fix author voice issues: {', '.join(author_voice_issues)}\n"
                f"Protect original idea: {', '.join(idea_drift)}"
            ),
            "auto_revision_count": new_count,
            "requires_human_review": False,
            "next_action": "article writer",
            "pipeline_log": [
                log_entry(
                    "Auto Draft Critic", "🤖",
                    f"Rejected draft (Rating: {rating}/10) → Auto-revision #{new_count}",
                    {
                        "rating": rating,
                        "markers": markers,
                        "tone_issues": tone_issues,
                        "author_voice_issues": author_voice_issues,
                        "idea_drift": idea_drift,
                        "unsupported_inventions": unsupported,
                        "feedback": feedback,
                    }
                )
            ]
        }

    # Approved
    print(f"\n[Auto Draft Critic] APPROVED the draft (Humanity Rating: {rating}/10)\n")
    return {
        "auto_revision_count": 0,
        "requires_human_review": False,
        "user_feedback": "",  # Clear old auto-feedback before prompting the user
        "next_action": "article approval",
        "pipeline_log": [
            log_entry(
                "Auto Draft Critic", "🤖",
                f"Approved draft (Rating: {rating}/10)",
                {"rating": rating}
            )
        ]
    }
