import json
from dataclasses import asdict, is_dataclass

from state import State
from utils.ask_llm import ask_llm
from utils.prompt_loader import get_prompt
from utils.pipeline_logger import log_entry


def _jsonable(value):
    """Helper to serialize dataclasses to dictionary format."""
    if is_dataclass(value):
        return asdict(value)
    return value


def auto_flow_critic(state: State):
    """
    Evaluates the outline/proposed flow generated by Flow Architect.
    Rejects flows with generic outlines or bad transitions to auto-correct them.
    Bypasses auto-revisions after 2 attempts to prevent infinite loops.
    """
    auto_count = state.get("auto_revision_count", 0)

    # Bypass critic to avoid getting stuck in loops
    if auto_count >= 2:
        return {
            "auto_revision_count": 0,
            "next_action": "flow approval",
            "pipeline_log": [
                log_entry(
                    "Auto Flow Critic", "🤖",
                    "Max automatic flow revisions (2) reached. Bypassing critic for user review.",
                    {}
                )
            ]
        }

    flow = state.get("proposed_flow")
    flow_str = json.dumps(_jsonable(flow), ensure_ascii=False, indent=2) if flow else ""

    prompt = get_prompt(
        "auto_flow_critic",
        summary=state["summary"],
        style_profile=json.dumps(state.get("style_profile", {}), ensure_ascii=False, indent=2),
        proposed_flow=flow_str
    )

    response = ask_llm(prompt=prompt, expect_json=True, task="auto_critic")
    approved = response.get("approved", True)
    rating = response.get("rating", 10.0)
    feedback = (response.get("feedback") or "").strip()

    if not approved and feedback:
        print(f"\n[🤖 Auto Flow Critic] REJECTED the outline (Rating: {rating}/10)")
        print(f"Feedback: {feedback}\n")
        return {
            "user_feedback": f"[Auto Critic Flow Revision]: {feedback}",
            "auto_revision_count": auto_count + 1,
            "next_action": "flow architect",
            "pipeline_log": [
                log_entry(
                    "Auto Flow Critic", "🤖",
                    f"Rejected outline (Rating: {rating}/10) → Auto-revision #{auto_count + 1}",
                    {"rating": rating, "feedback": feedback}
                )
            ]
        }

    # Approved
    print(f"\n[🤖 Auto Flow Critic] APPROVED the outline (Rating: {rating}/10)\n")
    return {
        "auto_revision_count": 0,
        "user_feedback": "",  # Clear old auto-feedback before prompting the user
        "next_action": "flow approval",
        "pipeline_log": [
            log_entry(
                "Auto Flow Critic", "🤖",
                f"Approved outline (Rating: {rating}/10)",
                {"rating": rating}
            )
        ]
    }


def auto_draft_critic(state: State):
    """
    Evaluates the draft for AI-generated tropes, sentence monotony, 
    cliche transitions, and poor metaphor integration.
    Rejects drafts scoring below 8.5/10 to perform auto-correction.
    Bypasses auto-revisions after 2 attempts to prevent loops.
    """
    auto_count = state.get("auto_revision_count", 0)

    # Bypass critic to avoid getting stuck in loops
    if auto_count >= 2:
        return {
            "auto_revision_count": 0,
            "next_action": "article approval",
            "pipeline_log": [
                log_entry(
                    "Auto Draft Critic", "🤖",
                    "Max automatic draft revisions (2) reached. Bypassing critic for user review.",
                    {}
                )
            ]
        }

    prompt = get_prompt(
        "auto_draft_critic",
        summary=state["summary"],
        style_profile=json.dumps(state.get("style_profile", {}), ensure_ascii=False, indent=2),
        draft=state.get("draft", "")
    )

    response = ask_llm(prompt=prompt, expect_json=True, task="auto_critic")
    approved = response.get("approved", True)
    rating = response.get("humanity_rating", 10.0)
    feedback = (response.get("feedback") or "").strip()
    markers = response.get("ai_markers_found", [])

    if not approved and feedback:
        print(f"\n[🤖 Auto Draft Critic] REJECTED the draft (Humanity Rating: {rating}/10)")
        if markers:
            print(f"AI Markers Found: {', '.join(markers)}")
        print(f"Feedback: {feedback}\n")
        
        return {
            "user_feedback": f"[Auto Critic Draft Revision]: {feedback}\n(Fix AI Markers: {', '.join(markers)})",
            "auto_revision_count": auto_count + 1,
            "next_action": "article writer",
            "pipeline_log": [
                log_entry(
                    "Auto Draft Critic", "🤖",
                    f"Rejected draft (Rating: {rating}/10) → Auto-revision #{auto_count + 1}",
                    {"rating": rating, "markers": markers, "feedback": feedback}
                )
            ]
        }

    # Approved
    print(f"\n[🤖 Auto Draft Critic] APPROVED the draft (Humanity Rating: {rating}/10)\n")
    return {
        "auto_revision_count": 0,
        "user_feedback": "",  # Clear old auto-feedback before prompting the user
        "next_action": "article approval",
        "pipeline_log": [
            log_entry(
                "Auto Draft Critic", "🤖",
                f"Approved draft (Rating: {rating}/10)",
                {"rating": rating}
            )
        ]
    }
