from dataclasses import dataclass, field


@dataclass
class Perspective:
    """
    Permanent entry stored in the Perspective Library.
    Defines how a discipline thinks.
    """

    name: str
    thinking_framework: str
    keywords: list[str]


@dataclass
class DiscoveredPerspective:
    """
    Temporary perspective discovered during one workflow execution.
    """

    name: str
    department: str
    reason: str

@dataclass
class Department:
    name: str
    description: str
    sub_departments: list[str]


@dataclass
class ExpertReport:
    """
    Temporary report generated by an expert employee for one article.
    """

    perspective: str
    department: str
    key_observations: list[str]
    risks_or_blindspots: list[str]
    writing_suggestions: list[str]
    web_sources: list[dict] = field(default_factory=list)


@dataclass
class WritingFlow:
    """
    Small editorial plan shown to the user before full drafting.
    """

    title_direction: str
    tone: str
    core_argument: str
    sections: list[str]
    approval_question: str
